In [1]:
#required imports
from sklearn.neural_network import MLPRegressor
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error  
from math import sqrt

In [2]:
#load features
features = pd.read_csv("features.csv")
features.head()

,Month,Season,Weekday,Holiday,Daily Weather,Daily Weather (Past),Humidity,Humidity (Past),Windspeed,Windspeed (Past),Apparent Temperature (Avg),Apparent Temperature (Avg) (Past),Rented Bikes,Rented Bikes (Future)
0,January,Winter,Monday,False,partly-cloudy-day,fog,0.88,0.94,1.59,0.55,46.740,36.295,281,279
1,January,Winter,Tuesday,False,partly-cloudy-day,partly-cloudy-day,0.86,0.88,2.07,1.59,42.150,46.740,279,274
2,January,Winter,Wednesday,False,clear-day,partly-cloudy-day,0.86,0.86,4.13,2.07,45.450,42.150,274,161
3,January,Winter,Thursday,False,rain,clear-day,0.87,0.86,3.60,4.13,46.200,45.450,161,270
4,January,Winter,Friday,False,partly-cloudy-day,rain,0.81,0.87,7.43,3.60,56.085,46.200,270,62

In [3]:
cleanup_nums = {"Month":   {"January": 1, "February": 2, "March": 3, "April": 4, "May": 5, "June": 6, "July": 7, "August": 8, "September": 9, "October": 10, "November": 11, "December": 12},
               "Season": {"Spring": 1, "Summer": 2, "Autumn": 3, "Winter": 4},
               "Weekday": {"Monday": 1, "Tuesday": 2, "Wednesday": 3, "Thursday": 4,
                                  "Friday": 5, "Saturday": 6, "Sunday":7 },
               "Daily Weather": {"clear-day": 1, "partly-cloudy-day": 2,"cloudy":3,"wind":4, "rain": 5, "fog": 6, "snow": 7},
               "Daily Weather (Past)": {"clear-day": 1, "partly-cloudy-day": 2,"cloudy":3,"wind":4, "rain": 5,"fog": 6, "snow": 7} }

In [4]:
features.replace(cleanup_nums, inplace=True)
features

,Month,Season,Weekday,Holiday,Daily Weather,Daily Weather (Past),Humidity,Humidity (Past),Windspeed,Windspeed (Past),Apparent Temperature (Avg),Apparent Temperature (Avg) (Past),Rented Bikes,Rented Bikes (Future)
0,1,4,1,False,2,fog,0.88,0.94,1.59,0.55,46.740,36.295,281,279
1,1,4,2,False,2,2,0.86,0.88,2.07,1.59,42.150,46.740,279,274
2,1,4,3,False,1,2,0.86,0.86,4.13,2.07,45.450,42.150,274,161
3,1,4,4,False,5,1,0.87,0.86,3.60,4.13,46.200,45.450,161,270
4,1,4,5,False,2,5,0.81,0.87,7.43,3.60,56.085,46.200,270,62
5,1,4,6,False,2,2,0.74,0.81,7.05,7.43,44.615,56.085,62,48
6,1,4,7,False,1,2,0.74,0.74,5.44,7.05,43.385,44.615,48,252
7,1,4,1,False,5,1,0.83,0.74,6.57,5.44,49.535,43.385,252,311
8,1,4,2,False,2,5,0.84,0.83,4.12,6.57,39.870,49.535,311,305
9,1,4,3,False,1,2,0.76,0.84,5.04,4.12,42.130,39.870,305,264
10,1,4,4,False,5,1,0.77,0.76,6.71,5.04,41.050,42.130,264,306
11,1,4,5,False,2,5,0.76,0.77,2.31,6.71,37.000,41.050,306,57
12,1,4,6,False,2,2,0.83,0.76,1.72,2.31,39.130,37.000,57,42
13,1,4,7,False,2,2,0.89,0.83,0.84,1.72,35.210,39.130,42,295
14,1,4,1,False,2,2,0.85,0.89,0.65,0.84,32.850,35.210,295,295
15,1,4,2,False,1,2,0.85,0.85,1.38,0.65,36.285,32.850,295,290
16,1,4,3,False,2,1,0.87,0.85,2.60,1.38,35.595,36.285,290,270
17,1,4,4,False,2,2,0.83,0.87,0.83,2.60,32.875,35.595,270,270
18,1,4,5,False,5,2,0.85,0.83,1.95,0.83,36.575,32.875,270,80
19,1,4,6,False,2,5,0.80,0.85,3.43,1.95,36.955,36.575,80,71
20,1,4,7,False,1,2,0.83,0.80,2.38,3.43,44.430,36.955,71,269
21,1,4,1,False,2,1,0.81,0.83,3.59,2.38,41.615,44.430,269,294
22,1,4,2,False,2,2,0.80,0.81,2.90,3.59,44.190,41.615,294,279
23,1,4,3,False,2,2,0.77,0.80,5.95,2.90,38.910,44.190,279,296
24,1,4,4,False,1,2,0.81,0.77,5.28,5.95,34.850,38.910,296,274
25,1,4,5,False,2,1,0.83,0.81,2.67,5.28,36.285,34.850,274,33
26,1,4,6,False,2,2,0.84,0.83,4.13,2.67,33.130,36.285,33,43
27,2,4,7,False,2,2,0.73,0.84,6.48,4.13,32.090,33.130,43,277
28,2,4,1,False,1,2,0.74,0.73,2.56,6.48,32.250,32.090,277,255
29,2,4,2,False,2,1,0.88,0.74,2.69,2.56,32.920,32.250,255,288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,2,4,1,False,2,1,0.88,0.84,7.84,7.46,39.640,50.450,291,321
1485,2,4,2,False,1,2,0.80,0.88,9.06,7.84,46.045,39.640,321,312
1486,2,4,3,False,2,1,0.80,0.80,10.00,9.06,48.360,46.045,312,298
1487,2,4,4,False,6,2,0.82,0.80,7.69,10.00,49.325,48.360,298,233
1488,2,4,5,False,6,fog,0.89,0.82,2.96,7.69,49.070,49.325,233,53
1489,2,4,6,False,6,fog,0.83,0.89,4.83,2.96,48.120,49.070,53,46
1490,2,4,7,False,2,fog,0.73,0.83,3.20,4.83,48.740,48.120,46,336
1491,2,4,1,False,2,2,0.60,0.73,3.64,3.20,50.815,48.740,336,370
1492,2,4,2,False,1,2,0.62,0.60,3.29,3.64,51.765,50.815,370,342
1493,2,4,3,False,1,1,0.71,0.62,2.76,3.29,52.640,51.765,342,325
1494,2,4,4,False,6,1,0.87,0.71,8.12,2.76,49.215,52.640,325,300
1495,3,1,5,False,2,fog,0.82,0.87,4.88,8.12,47.510,49.215,300,69
1496,3,1,6,False,4,2,0.84,0.82,10.17,4.88,51.345,47.510,69,30
1497,3,1,7,False,4,4,0.84,0.84,16.54,10.17,43.045,51.345,30,353
1498,3,1,1,False,2,4,0.76,0.84,14.23,16.54,41.135,43.045,353,348
1499,3,1,2,False,1,2,0.76,0.76,10.29,14.23,47.920,41.135,348,290
1500,3,1,3,False,2,1,0.85,0.76,14.22,10.29,44.875,47.920,290,317
1501,3,1,4,False,4,2,0.73,0.85,17.86,14.22,43.760,44.875,317,279
1502,3,1,5,False,1,4,0.80,0.73,10.03,17.86,42.645,43.760,279,52
1503,3,1,6,False,4,1,0.71,0.80,14.65,10.03,46.140,42.645,52,38
1504,3,1,7,False,4,4,0.74,0.71,13.12,14.65,39.315,46.140,38,314
1505,3,1,1,False,4,4,0.61,0.74,13.51,13.12,44.650,39.315,314,266
1506,3,1,2,False,4,4,0.84,0.61,15.80,13.51,37.800,44.650,266,297
1507,3,1,3,False,4,4,0.64,0.84,19.48,15.80,45.130,37.800,297,238
1508,3,1,4,False,4,4,0.71,0.64,16.31,19.48,50.685,45.130,238,258
1509,3,1,5,False,4,4,0.80,0.71,19.56,16.31,54.260,50.685,258,28
1510,3,1,6,False,4,4,0.80,0.80,20.50,19.56,42.860,54.260,28,41
1511,3,1,7,True,2,4,0.74,0.80,13.56,20.50,38.345,42.860,41,327
1512,3,1,1,True,1,2,0.73,0.74,7.53,13.56,43.780,38.345,327,323
1513,3,1,2,False,2,1,0.82,0.73,5.76,7.53,50.340,43.780,323,33

In [5]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1514 entries, 0 to 1513
Data columns (total 14 columns):
Month                                1514 non-null int64
Season                               1514 non-null int64
Weekday                              1514 non-null int64
Holiday                              1514 non-null bool
Daily Weather                        1514 non-null int64
Daily Weather (Past)                 1514 non-null object
Humidity                             1514 non-null float64
Humidity (Past)                      1514 non-null float64
Windspeed                            1514 non-null float64
Windspeed (Past)                     1514 non-null float64
Apparent Temperature (Avg)           1514 non-null float64
Apparent Temperature (Avg) (Past)    1514 non-null float64
Rented Bikes                         1514 non-null int64
Rented Bikes (Future)                1514 non-null int64
dtypes: bool(1), float64(6), int64(6), object(1)
memory usage: 155.3+ KB

In [6]:
features.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Month,1514.0,6.282034,3.512095,1.000,3.0000,6.0000,9.00000,12.00
Season,1514.0,2.530383,1.140814,1.000,1.0000,3.0000,4.00000,4.00
Weekday,1514.0,3.996697,2.001484,1.000,2.0000,4.0000,6.00000,7.00
Daily Weather,1514.0,2.492734,1.463009,1.000,2.0000,2.0000,2.00000,7.00
Humidity,1514.0,0.779703,0.092875,0.410,0.7125,0.7900,0.85000,0.97
Humidity (Past),1514.0,0.779848,0.092995,0.410,0.7125,0.7900,0.85000,0.97
Windspeed,1514.0,4.028626,3.025981,0.020,2.0425,3.2400,5.14500,20.50
Windspeed (Past),1514.0,4.025938,3.026238,0.020,2.0400,3.2400,5.13000,20.50
Apparent Temperature (Avg),1514.0,52.234709,10.871111,15.935,44.0775,52.3425,60.63375,81.48
Apparent Temperature (Avg) (Past),1514.0,52.250386,10.844270,19.145,44.0775,52.3700,60.63375,81.48
Rented Bikes,1514.0,248.739762,132.553232,12.000,92.0000,302.0000,357.00000,838.00
Rented Bikes (Future),1514.0,248.575958,132.666525,12.000,92.0000,302.0000,357.00000,838.00

In [7]:
#target variable
y = features['Rented Bikes'].tolist()
y

[281,
 279,
 274,
 161,
 270,
 62,
 48,
 252,
 311,
 305,
 264,
 306,
 57,
 42,
 295,
 295,
 290,
 270,
 270,
 80,
 71,
 269,
 294,
 279,
 296,
 274,
 33,
 43,
 277,
 255,
 288,
 248,
 249,
 50,
 64,
 297,
 308,
 289,
 292,
 229,
 52,
 60,
 262,
 279,
 290,
 239,
 220,
 53,
 40,
 290,
 290,
 254,
 306,
 281,
 63,
 76,
 286,
 302,
 305,
 298,
 303,
 87,
 70,
 312,
 307,
 311,
 349,
 307,
 65,
 58,
 247,
 327,
 308,
 305,
 313,
 54,
 71,
 279,
 314,
 313,
 221,
 301,
 69,
 32,
 283,
 266,
 284,
 257,
 49,
 43,
 65,
 81,
 295,
 312,
 294,
 273,
 89,
 84,
 310,
 323,
 330,
 324,
 282,
 38,
 41,
 302,
 346,
 356,
 342,
 332,
 75,
 67,
 334,
 341,
 312,
 329,
 315,
 36,
 29,
 46,
 293,
 317,
 310,
 284,
 92,
 82,
 339,
 358,
 382,
 264,
 301,
 88,
 100,
 271,
 329,
 286,
 335,
 335,
 66,
 83,
 92,
 331,
 296,
 334,
 261,
 101,
 56,
 269,
 331,
 305,
 83,
 310,
 95,
 102,
 332,
 378,
 378,
 381,
 309,
 96,
 95,
 361,
 411,
 367,
 337,
 323,
 93,
 79,
 291,
 348,
 371,
 339,
 312,
 124,
 97,
 360,
 388,
 421,
 350,
 352,
 117,
 90,
 375,
 386,
 451,
 838,
 359,
 136,
 98,
 268,
 368,
 297,
 378,
 316,
 123,
 132,
 298,
 400,
 406,
 375,
 228,
 106,
 53,
 316,
 349,
 355,
 342,
 302,
 108,
 114,
 322,
 346,
 369,
 775,
 327,
 126,
 158,
 374,
 365,
 352,
 337,
 266,
 109,
 110,
 339,
 337,
 338,
 329,
 303,
 149,
 100,
 229,
 310,
 271,
 254,
 287,
 104,
 95,
 52,
 249,
 335,
 334,
 356,
 95,
 80,
 306,
 365,
 381,
 346,
 354,
 105,
 91,
 320,
 323,
 287,
 312,
 342,
 105,
 107,
 308,
 206,
 351,
 300,
 352,
 100,
 102,
 324,
 368,
 366,
 382,
 356,
 91,
 108,
 333,
 304,
 350,
 384,
 368,
 102,
 98,
 364,
 368,
 357,
 346,
 325,
 92,
 96,
 365,
 402,
 175,
 355,
 312,
 63,
 80,
 359,
 331,
 181,
 292,
 159,
 81,
 90,
 343,
 355,
 221,
 333,
 286,
 49,
 84,
 323,
 344,
 346,
 362,
 310,
 39,
 71,
 320,
 329,
 344,
 294,
 309,
 48,
 51,
 298,
 271,
 332,
 336,
 288,
 73,
 52,
 295,
 300,
 362,
 332,
 297,
 63,
 59,
 283,
 291,
 328,
 297,
 274,
 42,
 44,
 302,
 293,
 285,
 324,
 258,
 58,
 55,
 260,
 231,
 205,
 64,
 77,
 51,
 44,
 57,
 111,
 73,
 65,
 38,
 26,
 29,
 283,
 308,
 310,
 227,
 296,
 38,
 58,
 313,
 308,
 333,
 339,
 282,
 72,
 71,
 326,
 327,
 345,
 319,
 238,
 71,
 63,
 336,
 316,
 321,
 309,
 288,
 50,
 43,
 321,
 313,
 327,
 332,
 286,
 52,
 51,
 279,
 305,
 317,
 318,
 307,
 52,
 52,
 314,
 305,
 287,
 295,
 245,
 49,
 50,
 310,
 353,
 347,
 334,
 286,
 52,
 52,
 330,
 305,
 302,
 350,
 303,
 54,
 63,
 372,
 374,
 267,
 336,
 310,
 81,
 72,
 380,
 365,
 359,
 369,
 273,
 80,
 80,
 379,
 362,
 363,
 342,
 72,
 53,
 36,
 55,
 296,
 343,
 361,
 300,
 74,
 89,
 339,
 337,
 324,
 312,
 298,
 74,
 68,
 368,
 352,
 376,
 377,
 196,
 66,
 92,
 344,
 404,
 424,
 440,
 312,
 72,
 52,
 344,
 377,
 374,
 401,
 319,
 90,
 66,
 67,
 380,
 437,
 410,
 368,
 111,
 118,
 404,
 263,
 351,
 399,
 382,
 84,
 104,
 416,
 400,
 338,
 385,
 385,
 89,
 90,
 369,
 431,
 398,
 394,
 387,
 84,
 103,
 70,
 163,
 325,
 341,
 319,
 91,
 133,
 395,
 376,
 391,
 395,
 392,
 101,
 55,
 350,
 338,
 392,
 373,
 298,
 85,
 103,
 169,
 376,
 374,
 314,
 334,
 92,
 104,
 369,
 391,
 370,
 391,
 296,
 73,
 105,
 380,
 436,
 425,
 406,
 355,
 88,
 106,
 365,
 372,
 353,
 410,
 351,
 84,
 97,
 384,
 397,
 403,
 408,
 312,
 89,
 116,
 353,
 399,
 274,
 350,
 309,
 112,
 156,
 313,
 313,
 356,
 367,
 319,
 133,
 130,
 350,
 380,
 374,
 351,
 335,
 98,
 112,
 372,
 389,
 361,
 384,
 221,
 63,
 100,
 347,
 366,
 343,
 362,
 264,
 93,
 77,
 90,
 384,
 381,
 375,
 367,
 61,
 106,
 414,
 393,
 402,
 386,
 169,
 77,
 85,
 370,
 385,
 407,
 383,
 385,
 111,
 101,
 371,
 376,
 412,
 398,
 374,
 60,
 82,
 403,
 423,
 389,
 383,
 339,
 79,
 87,
 399,
 399,
 357,
 324,
 361,
 83,
 62,
 345,
 370,
 383,
 368,
 338,
 90,
 89,
 342,
 365,
 381,
 361,
 311,
 56,
 78,
 372,
 391,
 393,
 412,
 307,
 63,
 51,
 283,
 386,
 179,
 355,
 335,
 37,
 54,
 323,
 351,
 382,
 374,
 325,
 53,
 39,
 302,
 365,
 367,
 390,
 340,
 77,
 60,
 327,
 372,
 380,
 366,
 312,
 66,
 61,
 357,
 365,
 376,
 388,
 344,
 34,
 60,
 367,
 357,
 382,
 371,
 316,
 44,
 57,
 321,
 340,
 267,
 243,
 127,
 17,
 80,
 38,
 49,
 73,
 77,
 68,
 22,
 20,
 34,
 221,
 326,
 335,
 288,
 59,
 43,
 575,
 372,
 359,
 328,
 253,
 23,
 29,
 252,
 393,
 354,
 358,
 297,
 38,
 58,
 359,
 361,
 363,
 353,
 295,
 70,
 39,
 360,
 300,
 315,
 357,
 304,
 56,
 46,
 367,
 378,
 369,
 321,
 244,
 45,
 38,
 309,
 328,
 335,
 309,
 289,
 63,
 67,
 362,
 366,
 383,
 306,
 275,
 37,
 55,
 315,
 358,
 339,
 351,
 227,
 92,
 32,
 358,
 361,
 312,
 343,
 317,
 81,
 56,
 406,
 379,
 328,
 359,
 315,
 71,
 76,
 381,
 367,
 358,
 356,
 315,
 65,
 87,
 374,
 374,
 365,
 392,
 316,
 91,
 110,
 365,
 381,
 340,
 288,
 51,
 58,
 63,
 61,
 370,
 378,
 380,
 325,
 66,
 71,
 379,
 374,
 366,
 363,
 299,
 64,
 57,
 57,
 401,
 364,
 351,
 339,
 81,
 78,
 374,
 366,
 423,
 399,
 338,
 81,
 79,
 310,
 404,
 293,
 344,
 270,
 82,
 84,
 404,
 421,
 406,
 421,
 346,
 71,
 77,
 73,
 380,
 387,
 376,
 296,
 93,
 84,
 389,
 152,
 390,
 369,
 321,
 94,
 94,
 388,
 406,
 438,
 458,
 377,
 96,
 88,
 398,
 412,
 401,
 421,
 349,
 73,
 97,
 389,
 340,
 373,
 381,
 366,
 121,
 118,
 359,
 404,
 438,
 417,
 341,
 103,
 110,
 399,
 359,
 355,
 436,
 321,
 86,
 83,
 418,
 401,
 402,
 393,
 318,
 59,
 90,
 337,
 414,
 347,
 358,
 296,
 61,
 95,
 363,
 301,
 240,
 301,
 289,
 87,
 110,
 347,
 387,
 166,
 376,
 334,
 79,
 119,
 357,
 403,
 379,
 221,
 245,
 104,
 99,
 267,
 352,
 321,
 343,
 253,
 80,
 89,
 134,
 368,
 320,
 345,
 326,
 91,
 71,
 337,
 362,
 363,
 381,
 191,
 73,
 62,
 335,
 369,
 391,
 390,
 307,
 65,
 76,
 367,
 419,
 378,
 402,
 353,
 95,
 79,
 307,
 428,
 396,
 401,
 267,
 73,
 72,
 371,
 375,
 405,
 334,
 336,
 67,
 92,
 374,
 418,
 369,
 404,
 350,
 92,
 ...]

In [8]:
len(y)

1514

In [9]:
#transorm non-numerical labels to numerical labels
#le = LabelEncoder()
#features.loc[:,'Month'] = le.fit_transform(features['Month'])
#features.loc[:,'Season'] = le.fit_transform(features['Season'])
#features.loc[:,'Weekday'] = le.fit_transform(features['Weekday'])
#features.loc[:,'Holiday'] = le.fit_transform(features['Holiday'])
#features.loc[:,'Daily Weather'] = le.fit_transform(features['Daily Weather'])
#features.loc[:,'Daily Weather (Past)'] = le.fit_transform(features['Daily Weather (Past)'])
#features.head()

In [10]:
features.shape

(1514, 14)

In [11]:
#Feature Matrix with past and today data
X=features.loc[:,['Month','Season','Weekday','Daily Weather','Daily Weather (Past)','Humidity','Humidity (Past)','Windspeed', 'Windspeed (Past)', 'Apparent Temperature (Avg)','Apparent Temperature (Avg) (Past)','Rented Bikes (Future)']]
X.head()

,Month,Season,Weekday,Daily Weather,Daily Weather (Past),Humidity,Humidity (Past),Windspeed,Windspeed (Past),Apparent Temperature (Avg),Apparent Temperature (Avg) (Past),Rented Bikes (Future)
0,1,4,1,2,fog,0.88,0.94,1.59,0.55,46.740,36.295,279
1,1,4,2,2,2,0.86,0.88,2.07,1.59,42.150,46.740,274
2,1,4,3,1,2,0.86,0.86,4.13,2.07,45.450,42.150,161
3,1,4,4,5,1,0.87,0.86,3.60,4.13,46.200,45.450,270
4,1,4,5,2,5,0.81,0.87,7.43,3.60,56.085,46.200,62

In [12]:
#Split into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

ValueError: could not convert string to float: fog

In [ ]:
#initialize MLPRegressor
mlp = MLPRegressor(
    hidden_layer_sizes=(10,5),  activation='relu', solver='lbfgs', alpha=0.001, batch_size='auto',
    learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=1000, shuffle=True,
    random_state=9, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
    early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

m = mlp.fit(X_train,y_train)

predictions = m.predict(X_test)

In [ ]:
#Print scores
print("Training set score: %f" % m.score(X_train, y_train))
print("Test set score: %f" % m.score(X_test, y_test))

In [ ]:
#Compare predicted and actual values
df = pd.DataFrame({'Actual': y_test, 'Predicted': predictions})  
df.head()

In [ ]:
#Returns the coefficient of determination R^2 of the prediction
"The accuracy of the model is {0:.3f}".format(mlp.score(X_train,y_train))

## Accuracy
Recommended from [Sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html#sklearn.neural_network.MLPRegressor)<br>
```python
score(X, y, sample_weight=None)
```
Returns the coefficient of determination R^2 of the prediction.

The coefficient R^2 is defined as (1 - u/v), where u is the residual sum of squares ((y_true - y_pred) ** 2).sum() and v is the total sum of squares ((y_true - y_true.mean()) ** 2).sum(). The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). A constant model that always predicts the expected value of y, disregarding the input features, would get a R^2 score of 0.0.

In [ ]:
#accuracy formular
a=df.loc[:,'Actual']
b=df.loc[:,'Predicted']
c= b.mean()
u= ((a-b)**2).sum()
v= ((a-c)**2).sum()
r= (1-(u/v))
result = sqrt(r)
result

## RMSE = Root Mean Square Error 
is a frequently used measure of the differences between values predicted by a model. 

It is the standard deviation of prediction errors.<br>
[RMSE](https://www.statisticshowto.datasciencecentral.com/rmse/) answers the question of how concentrated the data is around the line of best fit.
![](img/rmse.png)
Where:<br>
f = forecasts (expected values or unknown results)<br>
o = observed values (known results)

In [ ]:
#RMSE version 1
a=df.loc[:,'Actual']
b=df.loc[:,'Predicted']
rmse=sqrt(mean_squared_error(a, b))  
"The root mean square error of the model is {0:.3f}".format(rmse)

In [ ]:
#RMSE version 2
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())

rmse = rmse(a,b)
"The root mean square error of the model is {0:.3f}".format(rmse)

In [ ]:
##RMSE version 3
n = len(b)
rmse = np.linalg.norm(b - a) / np.sqrt(n)
"The root mean square error of the model is {0:.3f}".format(rmse)